version: 2
executorType: machine
stages:
  build:
    workDir: ~/docker.nginx-php-fpm-local
    steps:
      - checkout

      - run:
          command: |
            sudo apt-get remove docker docker-engine &&
            sudo apt-get update &&
            sudo apt-get install  apt-transport-https ca-certificates  curl software-properties-common &&
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &&
            sudo apt-get update &&
            sudo apt-get install docker-ce=17.03.0~ce-0~ubuntu-trusty
          name: Install docker

      - run: make container

      - run:
          # Complexity in getting name of docker image is result of shift in contents of .docker_image
          command: docker run -p 80:80 -d --name local -d $(sed 's/^.*drud/drud/' < .docker_image | sed 's/ .*$//')
          name: start container

      - run:
          shell: /bin/bash
          command: docker exec -it local php --version
          name: check php version

      - run:
          shell: /bin/bash
          command: docker exec -it local php /var/www/html/docroot/test/test-email.php
          name: test php mail

      - run:
          command: docker stop local
          name: stop container
