version: 2
executorType: machine
stages:
  build:
    workDir: ~/docker.nginx-php-fpm-local
    steps:
      - checkout

      - run: sudo apt-get -qq update && sudo apt-get -qq install -y realpath

      - run:
          command: docker version
          name: Display tool versions
          
      - run: make container

      - run:
          shell: /bin/bash
          command: make test
          name: make test
