version: 2
executorType: machine
stages:
  build:
    workDir: ~/docker.nginx-php-fpm-local
    environment:
      # Complexity in getting name of docker image is result of shift in contents of .docker_image
      CONTAINER: $(sed 's/^.*drud/drud/' < .docker_image | sed 's/ .*$//')
    steps:
      - type: checkout

      - type: shell
        command: make container
        name: make container

      - type: shell
        command: docker run -p 80:80 $CONTAINER
        name: start container

      - type: shell
        command: docker exec -it $CONTAINER php --version | grep "^PHP 7"
        name: check php version

      - type: shell
        command: docker exec -it $CONTAINER php /var/www/html/docroot/test/test-email.php | grep "Test email sent"
        name: test php mail

      - type: shell
        command: docker stop $CONTAINER
        name: stop container
