version: 2
executorType: machine
stages:
  build:
    workDir: ~/docker.nginx-php-fpm-local
    steps:
      - type: checkout

      - type: shell
        command: make container
        name: make container

      - type: shell
        # Complexity in getting name of docker image is result of shift in contents of .docker_image
        command: docker run -p 80:80 -d --name local -d $(sed 's/^.*drud/drud/' < .docker_image | sed 's/ .*$//')
        name: start container

      - type: shell
        command: docker exec -it local php --version | grep "^PHP 7"
        name: check php version

      - type: shell
        command: docker exec -it local php /var/www/html/docroot/test/test-email.php | grep "Test email sent"
        name: test php mail

      - type: shell
        command: docker stop local
        name: stop container
